name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
categories:
  - title: "🚀 Features"
    labels:
      - 'feature'
      - 'enhancement'
  - title: "🐛 Bug Fixes"
    labels:
      - 'bug'
      - 'bugfix'
      - 'fix'
  - title: "🛠️ Maintenance"
    labels:
      - 'refactor'
      - 'chore'
change-template: "- $TITLE (#$NUMBER) by @$AUTHOR"
change-title-escapes: '\<*_&'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## Changes in this release

  $CHANGES
