repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        exclude: "^(tests/|migrations/|venv/)"
      - id: end-of-file-fixer
        exclude: "^(tests/|migrations/|venv/)"
      - id: check-yaml
        exclude: "^(tests/|migrations/|venv/)"
      - id: check-docstring-first
        exclude: "^(tests/|migrations/|venv/)"
      - id: requirements-txt-fixer
        exclude: "^(tests/|migrations/|venv/)"

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        exclude: "^(tests/|migrations/|venv/)"

  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.2
    hooks:
      - id: flake8
        exclude: "^(tests/|migrations/|venv/)"

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        exclude: "^(tests/|migrations/|venv/)"

  - repo: https://github.com/PyCQA/pylint
    rev: v3.3.5
    hooks:
      - id: pylint
        additional_dependencies:
          - python-telegram-bot
        args: ["--disable=broad-exception-caught,import-error", "--jobs=4"]
        exclude: "^(tests/|migrations/|venv/|modules/)"
      - id: pylint
        name: pylint-modules
        additional_dependencies:
          - python-telegram-bot
        args: ["--disable=unused-import,unused-argument,broad-exception-caught,import-error"]
        files: ^modules/
